# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mcx_tracking_cam.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mcx_tracking_cam.proto',
  package='mcx_tracking_cam',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x16mcx_tracking_cam.proto\x12\x10mcx_tracking_cam\"8\n\x04\x42lob\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04type\x18\x02 \x02(\x05\x12\n\n\x02\x63x\x18\x03 \x02(\x05\x12\n\n\x02\x63y\x18\x04 \x02(\x05\".\n\x05\x42lobs\x12%\n\x05value\x18\x01 \x03(\x0b\x32\x16.mcx_tracking_cam.Blob\"8\n\x06Marker\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0f\n\x07rotVec3\x18\x02 \x03(\x01\x12\x11\n\ttransVec3\x18\x03 \x03(\x01\"2\n\x07Markers\x12\'\n\x05value\x18\x01 \x03(\x0b\x32\x18.mcx_tracking_cam.Marker\"+\n\x07Point2D\x12\n\n\x02id\x18\x01 \x02(\x05\x12\t\n\x01x\x18\x02 \x02(\x01\x12\t\n\x01y\x18\x03 \x02(\x01\"a\n\nProjection\x12(\n\x06origin\x18\x01 \x02(\x0b\x32\x18.mcx_tracking_cam.Marker\x12)\n\x06points\x18\x02 \x03(\x0b\x32\x19.mcx_tracking_cam.Point2D'
)




_BLOB = _descriptor.Descriptor(
  name='Blob',
  full_name='mcx_tracking_cam.Blob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mcx_tracking_cam.Blob.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='mcx_tracking_cam.Blob.type', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cx', full_name='mcx_tracking_cam.Blob.cx', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cy', full_name='mcx_tracking_cam.Blob.cy', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=100,
)


_BLOBS = _descriptor.Descriptor(
  name='Blobs',
  full_name='mcx_tracking_cam.Blobs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='mcx_tracking_cam.Blobs.value', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=148,
)


_MARKER = _descriptor.Descriptor(
  name='Marker',
  full_name='mcx_tracking_cam.Marker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mcx_tracking_cam.Marker.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotVec3', full_name='mcx_tracking_cam.Marker.rotVec3', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transVec3', full_name='mcx_tracking_cam.Marker.transVec3', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=206,
)


_MARKERS = _descriptor.Descriptor(
  name='Markers',
  full_name='mcx_tracking_cam.Markers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='mcx_tracking_cam.Markers.value', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=258,
)


_POINT2D = _descriptor.Descriptor(
  name='Point2D',
  full_name='mcx_tracking_cam.Point2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mcx_tracking_cam.Point2D.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='mcx_tracking_cam.Point2D.x', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='mcx_tracking_cam.Point2D.y', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=303,
)


_PROJECTION = _descriptor.Descriptor(
  name='Projection',
  full_name='mcx_tracking_cam.Projection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='origin', full_name='mcx_tracking_cam.Projection.origin', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='points', full_name='mcx_tracking_cam.Projection.points', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=402,
)

_BLOBS.fields_by_name['value'].message_type = _BLOB
_MARKERS.fields_by_name['value'].message_type = _MARKER
_PROJECTION.fields_by_name['origin'].message_type = _MARKER
_PROJECTION.fields_by_name['points'].message_type = _POINT2D
DESCRIPTOR.message_types_by_name['Blob'] = _BLOB
DESCRIPTOR.message_types_by_name['Blobs'] = _BLOBS
DESCRIPTOR.message_types_by_name['Marker'] = _MARKER
DESCRIPTOR.message_types_by_name['Markers'] = _MARKERS
DESCRIPTOR.message_types_by_name['Point2D'] = _POINT2D
DESCRIPTOR.message_types_by_name['Projection'] = _PROJECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Blob = _reflection.GeneratedProtocolMessageType('Blob', (_message.Message,), {
  'DESCRIPTOR' : _BLOB,
  '__module__' : 'mcx_tracking_cam_pb2'
  # @@protoc_insertion_point(class_scope:mcx_tracking_cam.Blob)
  })
_sym_db.RegisterMessage(Blob)

Blobs = _reflection.GeneratedProtocolMessageType('Blobs', (_message.Message,), {
  'DESCRIPTOR' : _BLOBS,
  '__module__' : 'mcx_tracking_cam_pb2'
  # @@protoc_insertion_point(class_scope:mcx_tracking_cam.Blobs)
  })
_sym_db.RegisterMessage(Blobs)

Marker = _reflection.GeneratedProtocolMessageType('Marker', (_message.Message,), {
  'DESCRIPTOR' : _MARKER,
  '__module__' : 'mcx_tracking_cam_pb2'
  # @@protoc_insertion_point(class_scope:mcx_tracking_cam.Marker)
  })
_sym_db.RegisterMessage(Marker)

Markers = _reflection.GeneratedProtocolMessageType('Markers', (_message.Message,), {
  'DESCRIPTOR' : _MARKERS,
  '__module__' : 'mcx_tracking_cam_pb2'
  # @@protoc_insertion_point(class_scope:mcx_tracking_cam.Markers)
  })
_sym_db.RegisterMessage(Markers)

Point2D = _reflection.GeneratedProtocolMessageType('Point2D', (_message.Message,), {
  'DESCRIPTOR' : _POINT2D,
  '__module__' : 'mcx_tracking_cam_pb2'
  # @@protoc_insertion_point(class_scope:mcx_tracking_cam.Point2D)
  })
_sym_db.RegisterMessage(Point2D)

Projection = _reflection.GeneratedProtocolMessageType('Projection', (_message.Message,), {
  'DESCRIPTOR' : _PROJECTION,
  '__module__' : 'mcx_tracking_cam_pb2'
  # @@protoc_insertion_point(class_scope:mcx_tracking_cam.Projection)
  })
_sym_db.RegisterMessage(Projection)


# @@protoc_insertion_point(module_scope)